### ISSUE TITLE
Cycle pumps

### ISSUE THREAD

**Issue by joostschouppe** [osmbe/cyclofix-docs#6]
## TODO

- [x] extend with other tags
- [ ] document on the docs website
- [ ] document on the wiki discussion page and put a link on the OSMBE riot

### Main tag

Decision:
- we will show everything with the tag `service:bicycle:pump=yes`
- for independent pumps, we will use `amenity=bicycle_repair_station + service:bicycle:pump=yes/no`
- for pumps offered at other places `service:bicycle:pump=yes` indicates that "has a free bicycle pump which can be used by anybody" (already like this on the wiki)
So we need three different icons?
- an independent pump (amenity=bicycle_repair_station + service:bicycle:pump=yes + [no other service:bicycle:* tags)
- a repair station with a pump (amenity=bicycle_repair_station + service:bicycle:pump=yes + [one or more other service:bicycle:* tags)
- another feature (most like a shop) with a free pump ( !amenity=bicycle_repair_station+ service:bicycle:pump=yes). This includes `amenity=compressed_air` that has been explicitely marked as oriented to cyclists)

Reasoning for independent pumps:

Option 1)
`amenity=bicycle_repair_station
service:bicycle:pump=yes/no`
downside: this is a little weird, as there is no "real" repair station**
but: a repair station with just this one service is relatively un-ambigious)

Option 2)
`amenity=compressed_air` + some clarifying tag
downside: it's hard to filter those meant for bicycles (there is more than one option to indicate this) and it makes it very hard for car-oriented data-users to filter away those NOT meant for cars

Note the subtags at https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcompressed_air aren't in the same logic as those for repair stations
